services:
  
  ghost:
    image: ghost:5-alpine
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: $DB_USER
      database__connection__password: $DB_PASS
      database__connection__database: $DB_NAME
      mail__transport: $MAIL_TRANSPORT
      mail__options__service: $MAIL_SERVICE
      mail__options__host: $MAIL_HOST
      mail__options__port: $MAIL_PORT
      mail__options__secure: $MAIL_SECURE
      mail__options__auth__user: $MAIL_USER
      mail__options__auth__pass: $MAIL_PASS
      mail__from: $MAIL_FROM
      url: $URL
    volumes:
      - content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
    volumes:
      - db:/var/lib/mysql

volumes:
  content:
  db: